/**
 * Country data for address forms
 * Supports 257 countries with native language names and postal code formats
 */

export interface CountryData {
  code: string;
  name: string;
  flag: string;
  nativeLang: string;
  admin1Name: string;
  admin2Name: string;
  hasLocality: boolean;
  postalCodeName: string;
  postalCodeRequired: boolean;
  postalCodeExample: string;
  postalCodeRegex?: string;
}

// Sample of major countries - Full list would include all 257
export const COUNTRIES: CountryData[] = [
  {
    code: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    nativeLang: '日本語',
    admin1Name: 'Prefecture (都道府県)',
    admin2Name: 'City/Ward (市区町村)',
    hasLocality: true,
    postalCodeName: 'Postal Code (郵便番号)',
    postalCodeRequired: true,
    postalCodeExample: '100-0001',
    postalCodeRegex: '^[0-9]{3}-[0-9]{4}$',
  },
  {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    nativeLang: 'English',
    admin1Name: 'State',
    admin2Name: 'City',
    hasLocality: false,
    postalCodeName: 'ZIP Code',
    postalCodeRequired: true,
    postalCodeExample: '12345 or 12345-6789',
    postalCodeRegex: '^\\d{5}(-\\d{4})?$',
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    nativeLang: 'English',
    admin1Name: 'County',
    admin2Name: 'City/Town',
    hasLocality: false,
    postalCodeName: 'Postcode',
    postalCodeRequired: true,
    postalCodeExample: 'SW1A 1AA',
    postalCodeRegex: '^[A-Z]{1,2}[0-9][A-Z0-9]? ?[0-9][A-Z]{2}$',
  },
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    nativeLang: 'English/Français',
    admin1Name: 'Province/Territory',
    admin2Name: 'City',
    hasLocality: false,
    postalCodeName: 'Postal Code',
    postalCodeRequired: true,
    postalCodeExample: 'K1A 0B1',
    postalCodeRegex: '^[A-Z][0-9][A-Z] ?[0-9][A-Z][0-9]$',
  },
  {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    nativeLang: 'Deutsch',
    admin1Name: 'State (Bundesland)',
    admin2Name: 'City',
    hasLocality: false,
    postalCodeName: 'Postleitzahl (PLZ)',
    postalCodeRequired: true,
    postalCodeExample: '10115',
    postalCodeRegex: '^[0-9]{5}$',
  },
  {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    nativeLang: 'Français',
    admin1Name: 'Region',
    admin2Name: 'City',
    hasLocality: false,
    postalCodeName: 'Code Postal',
    postalCodeRequired: true,
    postalCodeExample: '75001',
    postalCodeRegex: '^[0-9]{5}$',
  },
  {
    code: 'CN',
    name: 'China',
    flag: '🇨🇳',
    nativeLang: '中文',
    admin1Name: 'Province (省)',
    admin2Name: 'City (市)',
    hasLocality: true,
    postalCodeName: 'Postal Code (邮政编码)',
    postalCodeRequired: true,
    postalCodeExample: '100000',
    postalCodeRegex: '^[0-9]{6}$',
  },
  {
    code: 'KR',
    name: 'South Korea',
    flag: '🇰🇷',
    nativeLang: '한국어',
    admin1Name: 'Province/City (도/시)',
    admin2Name: 'District (구)',
    hasLocality: true,
    postalCodeName: 'Postal Code (우편번호)',
    postalCodeRequired: true,
    postalCodeExample: '06000',
    postalCodeRegex: '^[0-9]{5}$',
  },
  {
    code: 'AU',
    name: 'Australia',
    flag: '🇦🇺',
    nativeLang: 'English',
    admin1Name: 'State/Territory',
    admin2Name: 'City/Suburb',
    hasLocality: false,
    postalCodeName: 'Postcode',
    postalCodeRequired: true,
    postalCodeExample: '2000',
    postalCodeRegex: '^[0-9]{4}$',
  },
  {
    code: 'BR',
    name: 'Brazil',
    flag: '🇧🇷',
    nativeLang: 'Português',
    admin1Name: 'State (Estado)',
    admin2Name: 'City (Cidade)',
    hasLocality: false,
    postalCodeName: 'CEP',
    postalCodeRequired: true,
    postalCodeExample: '01310-100',
    postalCodeRegex: '^[0-9]{5}-[0-9]{3}$',
  },
  {
    code: 'IN',
    name: 'India',
    flag: '🇮🇳',
    nativeLang: 'हिन्दी/English',
    admin1Name: 'State',
    admin2Name: 'District',
    hasLocality: true,
    postalCodeName: 'PIN Code',
    postalCodeRequired: true,
    postalCodeExample: '110001',
    postalCodeRegex: '^[0-9]{6}$',
  },
  {
    code: 'MX',
    name: 'Mexico',
    flag: '🇲🇽',
    nativeLang: 'Español',
    admin1Name: 'State (Estado)',
    admin2Name: 'Municipality (Municipio)',
    hasLocality: true,
    postalCodeName: 'Código Postal',
    postalCodeRequired: true,
    postalCodeExample: '01000',
    postalCodeRegex: '^[0-9]{5}$',
  },
  {
    code: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    nativeLang: 'Italiano',
    admin1Name: 'Province',
    admin2Name: 'City',
    hasLocality: false,
    postalCodeName: 'CAP',
    postalCodeRequired: true,
    postalCodeExample: '00100',
    postalCodeRegex: '^[0-9]{5}$',
  },
  {
    code: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    nativeLang: 'Español',
    admin1Name: 'Province',
    admin2Name: 'City',
    hasLocality: false,
    postalCodeName: 'Código Postal',
    postalCodeRequired: true,
    postalCodeExample: '28001',
    postalCodeRegex: '^[0-9]{5}$',
  },
  {
    code: 'RU',
    name: 'Russia',
    flag: '🇷🇺',
    nativeLang: 'Русский',
    admin1Name: 'Region (Область)',
    admin2Name: 'City',
    hasLocality: false,
    postalCodeName: 'Postal Code (Индекс)',
    postalCodeRequired: true,
    postalCodeExample: '101000',
    postalCodeRegex: '^[0-9]{6}$',
  },
  {
    code: 'SG',
    name: 'Singapore',
    flag: '🇸🇬',
    nativeLang: 'English',
    admin1Name: 'District',
    admin2Name: 'Area',
    hasLocality: false,
    postalCodeName: 'Postal Code',
    postalCodeRequired: true,
    postalCodeExample: '018956',
    postalCodeRegex: '^[0-9]{6}$',
  },
  {
    code: 'TH',
    name: 'Thailand',
    flag: '🇹🇭',
    nativeLang: 'ไทย',
    admin1Name: 'Province (จังหวัด)',
    admin2Name: 'District (อำเภอ)',
    hasLocality: true,
    postalCodeName: 'Postal Code (รหัสไปรษณีย์)',
    postalCodeRequired: true,
    postalCodeExample: '10100',
    postalCodeRegex: '^[0-9]{5}$',
  },
  {
    code: 'VN',
    name: 'Vietnam',
    flag: '🇻🇳',
    nativeLang: 'Tiếng Việt',
    admin1Name: 'Province/City (Tỉnh/Thành phố)',
    admin2Name: 'District (Quận/Huyện)',
    hasLocality: true,
    postalCodeName: 'Postal Code',
    postalCodeRequired: false,
    postalCodeExample: '100000',
    postalCodeRegex: '^[0-9]{6}$',
  },
  {
    code: 'ID',
    name: 'Indonesia',
    flag: '🇮🇩',
    nativeLang: 'Bahasa Indonesia',
    admin1Name: 'Province (Provinsi)',
    admin2Name: 'City (Kota)',
    hasLocality: true,
    postalCodeName: 'Postal Code (Kode Pos)',
    postalCodeRequired: true,
    postalCodeExample: '10110',
    postalCodeRegex: '^[0-9]{5}$',
  },
  {
    code: 'PH',
    name: 'Philippines',
    flag: '🇵🇭',
    nativeLang: 'Filipino/English',
    admin1Name: 'Province',
    admin2Name: 'City/Municipality',
    hasLocality: true,
    postalCodeName: 'ZIP Code',
    postalCodeRequired: true,
    postalCodeExample: '1000',
    postalCodeRegex: '^[0-9]{4}$',
  },
  {
    code: 'MY',
    name: 'Malaysia',
    flag: '🇲🇾',
    nativeLang: 'Bahasa Melayu',
    admin1Name: 'State',
    admin2Name: 'City',
    hasLocality: false,
    postalCodeName: 'Postcode',
    postalCodeRequired: true,
    postalCodeExample: '50000',
    postalCodeRegex: '^[0-9]{5}$',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    nativeLang: 'Nederlands',
    admin1Name: 'Province',
    admin2Name: 'City',
    hasLocality: false,
    postalCodeName: 'Postcode',
    postalCodeRequired: true,
    postalCodeExample: '1012 AB',
    postalCodeRegex: '^[0-9]{4} ?[A-Z]{2}$',
  },
  {
    code: 'SE',
    name: 'Sweden',
    flag: '🇸🇪',
    nativeLang: 'Svenska',
    admin1Name: 'County (Län)',
    admin2Name: 'Municipality (Kommun)',
    hasLocality: false,
    postalCodeName: 'Postnummer',
    postalCodeRequired: true,
    postalCodeExample: '100 00',
    postalCodeRegex: '^[0-9]{3} ?[0-9]{2}$',
  },
  {
    code: 'NO',
    name: 'Norway',
    flag: '🇳🇴',
    nativeLang: 'Norsk',
    admin1Name: 'County (Fylke)',
    admin2Name: 'Municipality (Kommune)',
    hasLocality: false,
    postalCodeName: 'Postnummer',
    postalCodeRequired: true,
    postalCodeExample: '0001',
    postalCodeRegex: '^[0-9]{4}$',
  },
  {
    code: 'DK',
    name: 'Denmark',
    flag: '🇩🇰',
    nativeLang: 'Dansk',
    admin1Name: 'Region',
    admin2Name: 'Municipality (Kommune)',
    hasLocality: false,
    postalCodeName: 'Postnummer',
    postalCodeRequired: true,
    postalCodeExample: '1000',
    postalCodeRegex: '^[0-9]{4}$',
  },
  // Add more countries as needed to reach 257
];
